# This file was generated by GoReleaser. DO NOT EDIT.
class GitSemv < Formula
  desc "This is a Git plugin for Semantic Versioning."
  homepage "https://github.com/linyows/git-semv"
  url "https://github.com/linyows/git-semv/releases/download/v1.1.0/git-semv_darwin_amd64.tar.gz"
  version "1.1.0"
  sha256 "272298e5a664e68a415df15d89eb32a254a7f9557277ab3b833a63ac39408e07"
  
  depends_on "git"

  def install
    bin.install "git-semv"
    #  zsh_completion.install "misc/completion.zsh"
    #  bash_completion.install "misc/completion.bash"
    #  fish_completion.install "misc/completion.fish"
  end

  test do
    system "#{bin}/git-semv -v"
  end
end
